apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: example1
spec:
  containers:
    - name: nginx
      image: nginx
    - name: apache
      image: apache
    - name: busybox
      image: busybox